### ISSUE TITLE
Code problems！！！

### ISSUE THREAD

**Issue by hongge831** [Christophe-Jia/mislabel-detection#1]
Hi，firstly it is a good work in noise leanring. After reading your code, I notice that there are several typo or issues in you code.
For instances, in runner.py, line 716 the variable `mode` is not specific， and line 799 in runner.py, parameters of the  function `transfor_and_save ` mismatch with the function entity in the utils.py!!!
Hope you can fix them and upated you code thanks alot.

**Comment by Christophe-Jia** [comment]
HI, hongge. Thanks for you pointing out code typo. I have already fixed them and will update soon.

**Comment by Christophe-Jia** [comment]
Hi, I've already uploaded the latest code, have a check~
